### ISSUE TITLE
Error while diff two files

### ISSUE THREAD

**Issue by vsc1t** [cytopia/ansible-module-diff#3]
The full traceback is:
Traceback (most recent call last):
  File "/home/vik/.ansible/tmp/ansible-tmp-1552865637.1434965-8627458176773/AnsiballZ_difference.py", line 114, in <module>
    _ansiballz_main()
  File "/home/vik/.ansible/tmp/ansible-tmp-1552865637.1434965-8627458176773/AnsiballZ_difference.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vik/.ansible/tmp/ansible-tmp-1552865637.1434965-8627458176773/AnsiballZ_difference.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_difference_payload__2_x8wp3/__main__.py", line 385, in <module>
  File "/tmp/ansible_difference_payload__2_x8wp3/__main__.py", line 359, in main
  File "/tmp/ansible_difference_payload__2_x8wp3/__main__.py", line 259, in retrieve_input
AttributeError: 'str' object has no attribute 'decode'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/vik/.ansible/tmp/ansible-tmp-1552865637.1434965-8627458176773/AnsiballZ_difference.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/vik/.ansible/tmp/ansible-tmp-1552865637.1434965-8627458176773/AnsiballZ_difference.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vik/.ansible/tmp/ansible-tmp-1552865637.1434965-8627458176773/AnsiballZ_difference.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_difference_payload__2_x8wp3/__main__.py\", line 385, in <module>\n  File \"/tmp/ansible_difference_payload__2_x8wp3/__main__.py\", line 359, in main\n  File \"/tmp/ansible_difference_payload__2_x8wp3/__main__.py\", line 259, in retrieve_input\nAttributeError: 'str' object has no attribute 'decode'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Also, ansible pushed me to rename diff to difference.

- name: Diff two files
  difference:
    source: /home/vik/PycharmProjects/ansible/test_backup_manual/test_diff.txt
    target: /home/vik/PycharmProjects/ansible/test_backup_manual/test_diff2.txt
    source_type: file
    target_type: file
    diff: raw
  register: something
- debug:
    msg: "{{something}}"

**Comment by vsc1t** [comment]
# Input is a file
    if input_type == 'file':
        # __import__('pdb').set_trace()
        with open(input_data, 'rt') as fpt:
            # input_data = fpt.read().decode("UTF-8")
            input_data = fpt.read()
now it work

**Comment by cytopia** [comment]
@vsc1t thanks for the issue. Which part did you change in the *.py file?

**Comment by RanFirstTry** [comment]
I had the same error as the commenter above. The issue is in line 249 of diff.py, in which the ftp.read().decode("UTF-8") is attempting to decode an already decoded string. I dropped the .decode part and it works.
